FROM tiangolo/uwsgi-nginx-flask:python3.6

# update ca-certificates
RUN apt update -y && apt install ca-certificates -y

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt

#ADD ./app /app

ENV STATIC_URL /main/static
# Absolute path in where the static files wil be
ENV STATIC_PATH /app/main/static

WORKDIR /
ENV PYTHONPATH = /
