version: '2'
services:
  mongo:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data_container:/data/db


  webapi:
    image: webapi
    restart: always
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - mongo

volumes:
  mongodb_data_container:
